---
tasks file for 2do_parcial
- name: Crear directorio /tmp/2do_parcial/alumnos
  file:
    path: /tmp/2do_parcial/alumnos
    state: directory
    mode: '0755'

- name: Crear directorio /tmp/2do_parcial/equipo
  file:
    path: /tmp/2do_parcial/equipo
    state: directory
    mode: '0755'

- name: Crear archivo datos_alumno.txt
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumnos/datos_alumno.txt

- name: Crear archivo datos_equipo.txt
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt

- name: Configurar sudoers para 2PSupervisores sin contraseña
  lineinfile:
    path: /etc/sudoers
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'


